### ISSUE TITLE
Cannot run on Julia v 1.9.0

### ISSUE THREAD

**Issue by yzpan1** [gangwug/Oslops#1]
Dear Gang,

I'm trying to run the protocol in Julia 1.9.0. I keep running into errors such as 
"LoadError: ArgumentError: Package CYCLOPS_2a_AutoEncoderModule not found in current path."
"LoadError: syntax: "module" at /home/kaylab/Documents/projects/20230403_TCGA_BRCA/Oslops/CYCLOPS_2a_AutoEncoderModule.jl:1 expected "end", got "Input_Layer""
I think this might due to big versinon differences... Can you please update the code to be compatible with 1.9.0?

Thank you!
Yuanzhong

**Comment by gangwug** [comment]
Hi Yuanzhong,

Yes, this is a version issue. I would suggest you contact Dr. Ron Anafi ***@***.******@***.***>) for a updated CYCLOPS version.

Best,
Gang

From: Yuanzhong Pan ***@***.***>
Date: Tuesday, May 23, 2023 at 8:12 PM
To: gangwug/Oslops ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [gangwug/Oslops] Cannot run on Julia v 1.9.0 (Issue #1)

Dear Gang,

I'm trying to run the protocol in Julia 1.9.0. I keep running into errors such as
"LoadError: ArgumentError: Package CYCLOPS_2a_AutoEncoderModule not found in current path."
"LoadError: syntax: "module" at /home/kaylab/Documents/projects/20230403_TCGA_BRCA/Oslops/CYCLOPS_2a_AutoEncoderModule.jl:1 expected "end", got "Input_Layer""
I think this might due to big versinon differences... Can you please update the code to be compatible with 1.9.0?

Thank you!
Yuanzhong

**Comment by cby01** [comment]
Dear Gang,
       Could you upload the environment of Julia v0.3 with additional packages? Currently, this version is no longer able to install additional packages.

**Comment by gangwug** [comment]
Dr. Ron Ananfi (https://github.com/ranafi) has a new version of CYCLOPS (https://www.biorxiv.org/content/10.1101/2023.05.17.540386v1), I suggest contacting him for the new version.

**Comment by gangwug** [comment]
Done.
